### ISSUE TITLE
Bug Report: Server crash when logging out

### ISSUE THREAD

**Issue by Silencx** [LyquidQrystal/GFFM#2]
Issue:
The server crashes when a player logs out while earning friendship points through the "Friendship from Melodies" mechanic. This seems to be caused by a NullPointerException when trying to access a player reference that no longer exists.

Steps to Reproduce:
- Start the "Friendship from Melodies" process by playing music.
- Log out of the server while the process is still running.
- The server will crash.

Error Log:
``java.lang.NullPointerException:` Cannot invoke "net.minecraft.class_1657.method_5628()" because "player" is null
at knot//com.cobblemon.mod.common.entity.pokemon.PokemonEntity.handler$bgj000$gain_friendship_from_melodies$tickInject(PokemonEntity.java:2563)
at knot//com.cobblemon.mod.common.entity.pokemon.PokemonEntity.method_5773(PokemonEntity.java)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:283)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)``

**Comment by LyquidQrystal** [comment]
Thanks for the bug report, I'll look into it

**Comment by LyquidQrystal** [comment]
I've uploaded a new version. Please let me know if there is any bug.
